# Generated by Django 3.2.4 on 2021-06-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_patterns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('gallery_link', models.CharField(max_length=200)),
                ('checked_date', models.DateTimeField(verbose_name='date checked')),
            ],
        ),
    ]
