# Generated by Django 3.2.4 on 2021-06-06 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_currentpattern_galleries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleries',
            name='checked_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='links',
            name='checked_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
