# Generated by Django 3.2.4 on 2021-06-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20210606_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleries',
            name='img_tag',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='links',
            name='img_tag',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
