# Generated by Django 3.2.4 on 2021-06-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20210606_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleries',
            name='checked_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='checked_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
