# Generated by Django 3.2.4 on 2021-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20210606_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleries',
            name='status',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='links',
            name='status',
            field=models.IntegerField(default=200),
        ),
    ]
