# Generated by Django 3.2.4 on 2021-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_lastviewedgallerie_lastviewedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastviewedgallerie',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lastviewedimage',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
