# Generated by Django 3.2.4 on 2021-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20210610_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleries',
            name='name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='links',
            name='name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
